<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="4" errors="1" failures="1" skip="1"><testcase classname="test_skip" name="test_ok" time="0.002" /><testcase classname="test_skip" name="test_err" time="0.002"><error type="exceptions.Exception" message="oh no"><![CDATA[Traceback (most recent call last):
  File "/usr/local/Cellar/jython/2.5.1/libexec/Lib/unittest.py", line 260, in run
    testMethod()
  File "/private/tmp/nose_release_1.1.2/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/private/tmp/nose_release_1.1.2/functional_tests/doc_tests/test_xunit_plugin/support/test_skip.py", line 7, in test_err
    raise Exception("oh no")
Exception: oh no
]]></error></testcase><testcase classname="test_skip" name="test_fail" time="0.003"><failure type="exceptions.AssertionError" message="bye"><![CDATA[Traceback (most recent call last):
  File "/usr/local/Cellar/jython/2.5.1/libexec/Lib/unittest.py", line 260, in run
    testMethod()
  File "/private/tmp/nose_release_1.1.2/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/private/tmp/nose_release_1.1.2/functional_tests/doc_tests/test_xunit_plugin/support/test_skip.py", line 10, in test_fail
    assert False, "bye"
AssertionError: bye
]]></failure></testcase><testcase classname="test_skip" name="test_skip" time="0.002"><skipped type="nose.plugins.skip.SkipTest" message="not me"><![CDATA[Traceback (most recent call last):
  File "/usr/local/Cellar/jython/2.5.1/libexec/Lib/unittest.py", line 260, in run
    testMethod()
  File "/private/tmp/nose_release_1.1.2/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/private/tmp/nose_release_1.1.2/functional_tests/doc_tests/test_xunit_plugin/support/test_skip.py", line 13, in test_skip
    raise SkipTest("not me")
SkipTest: not me
]]></skipped></testcase></testsuite>